#!/bin/sh

#
# Randomizes the root password on first boot
#
# * When the file /root/firstboot is present, this script will
#   randomize the root password.
#
#   who: delano@solutious.com
#  when: 2009-03-13
#

# NOTE: Works on Gentoo
# TODO: Fix for debian

if [ -f "/root/firstrun" ] ; then
  dd if=/dev/urandom count=50|md5sum|passwd --stdin root
  rm -f /root/firstrun
else
  echo "* Firstrun *" && touch /root/firstrun
fi

